-- This script assumes you have the 'dreams' table already.

-- 1. Create a table to store unique tags (if it doesn't exist)
CREATE TABLE IF NOT EXISTS public.tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL -- Ensures every tag has a type
);

-- 2. Create a join table to link dreams and tags (if it doesn't exist)
CREATE TABLE IF NOT EXISTS public.dream_tags (
  dream_id BIGINT NOT NULL REFERENCES public.dreams(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  PRIMARY KEY (dream_id, tag_id)
);

-- 3. Enable RLS and create read policies (run if you haven't before)
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public tags are viewable by everyone." ON public.tags FOR SELECT USING ( true );

ALTER TABLE public.dream_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public dream_tags are viewable by everyone." ON public.dream_tags FOR SELECT USING ( true );
